export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  ADD_LIKED_ITEM: "ADD_LIKED_ITEM",
  REMOVE_LIKED_ITEM: "REMOVE_LIKED_ITEM",
  ADD_POSTED_ITEM: "ADD_POSTED_ITEM",
  REMOVE_POSTED_ITEM: "REMOVE_POSTED_ITEM",
};
